In [4]:
import numpy as np


In [5]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)


In [6]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [9]:
#ans  Yes, there is a difference in the data type of the list_ and array_list variables. The list_ is a regular
#     Python list containing string elements, while array_list is a NumPy array. The elements in the NumPy array 
#     are of type string as well, but the array itself has a specific data type that NumPy assigns.

In [10]:
array_list.dtype

dtype('int64')

In [11]:
type(list_)

list

Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
list_

[1, 2, 3, 4, 5]

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [23]:
array_list.dtype

dtype('int64')

In [26]:
type(list_)

list

In [29]:
for elem in list_:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [30]:
array_list = np.array(object = list_, dtype = int)

In [31]:
list_

['1', '2', '3', '4', '5']

In [33]:
array_list

array([1, 2, 3, 4, 5])

Consider the below code to answer further questions:

In [34]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [36]:
num_array.shape


(2, 3)

In [37]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [44]:
arr1 = np.random.randint(0,1 , (3,3))

In [45]:
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
Data1 = np.array([1,1,1,1,1])

In [ ]:
np.diag